type PoolManager @entity(immutable: false) {
  # Contract address
  id: ID!

  # Pair count
  pairCount: BigInt!

  # Transaction count
  txCount: BigInt!

  # Token count
  tokenCount: BigInt!

  # Pairs
  lbPairs: [LBPair!]! @derivedFrom(field: "factory")

  # Tokens
  tokens: [Token!]! @derivedFrom(field: "factory")
}

type Token @entity(immutable: false) {
  # token address
  id: ID!

  # factory
  factory: PoolManager!

  # mirrored from the smart contract
  symbol: String!
  name: String!
  decimals: BigInt!

  # used for other stats like marketcap
  totalSupply: BigInt!

  # transactions across all pairs
  txCount: BigInt!

  # Base pairs
  basePairs: [LBPair!]! @derivedFrom(field: "tokenX")

  # Quote pairs
  quotePairs: [LBPair!]! @derivedFrom(field: "tokenY")
}

type LBPair @entity(immutable: false) {
  # Contract address
  id: ID!

  # Factory
  factory: PoolManager!

  # Name
  name: String!

  # Base Fee
  baseFeePct: BigDecimal!

  # mirrored from the smart contract
  tokenX: Token!
  tokenY: Token!
  parameters: Bytes!
  activeId: Int!

  # hooks registration bitmap
  hooksRegistration: Bytes!
  # bin step
  binStep: BigInt!

  # hooks address
  hooks: String!

  reserveX: BigDecimal!
  reserveY: BigDecimal!

  # Price in terms of the asset pair
  tokenXPrice: BigDecimal!
  tokenYPrice: BigDecimal!

  txCount: BigInt!

  bins: [Bin!]! @derivedFrom(field: "lbPair")

  # Transactions
  mints: [Mint!]! @derivedFrom(field: "lbPair")
  burns: [Burn!]! @derivedFrom(field: "lbPair")
  swaps: [Swap!]! @derivedFrom(field: "lbPair")

  # Created at
  timestamp: BigInt!
  block: BigInt!
}

type Bin @entity(immutable: false) {
  id: ID! # lbPair address + # + binId
  lbPair: LBPair!

  priceX: BigDecimal!
  priceY: BigDecimal!

  liquidity: BigInt!
  totalSupply: BigInt!
  reserveX: BigDecimal!
  reserveY: BigDecimal!

  binId: Int!
}

type Transaction @entity(immutable: true) {
  # transaction hash
  id: ID!

  # block info
  blockNumber: Int!
  timestamp: Int!

  mints: [Mint!]! @derivedFrom(field: "transaction")
  burns: [Burn!]! @derivedFrom(field: "transaction")
  swaps: [Swap!]! @derivedFrom(field: "transaction")
}

type Mint @entity(immutable: true) {
  # transaction hash + "#" + index in mints Transaction array
  id: ID!
  transaction: Transaction!
  timestamp: Int! # need this to pull recent txns for specific token or pair
  # pair
  lbPair: LBPair!

  # populated from the Mint event
  sender: Bytes!
  recipient: Bytes!
  origin: Bytes!
  idsCount: Int!
  minId: Int!
  maxId: Int!
  salt: Bytes!

  amountX: BigDecimal!
  amountY: BigDecimal!

  logIndex: BigInt!
}

type Burn @entity(immutable: true) {
  # transaction hash + "#" + index in burns Transaction array
  id: ID!
  transaction: Transaction!
  timestamp: Int! # need this to pull recent txns for specific token or pair
  # pair
  lbPair: LBPair!

  # populated from the Mint event
  sender: Bytes!
  recipient: Bytes!
  origin: Bytes!
  idsCount: Int!
  minId: Int!
  maxId: Int!
  salt: Bytes!

  amountX: BigDecimal!
  amountY: BigDecimal!

  logIndex: BigInt!
}

type Swap @entity(immutable: true) {
  # transaction hash + "#" + index in swaps Transaction array
  id: ID!
  transaction: Transaction!
  timestamp: Int! # need this to pull recent txns for specific token or pair
  # pair
  lbPair: LBPair!

  # populated from the Swap event
  sender: Bytes!
  recipient: Bytes!
  origin: Bytes!
  activeId: Int!

  amountXIn: BigDecimal!
  amountYIn: BigDecimal!
  amountXOut: BigDecimal!
  amountYOut: BigDecimal!

  logIndex: BigInt!
}